            - name: Get Vercel Deployment
  # You may pin to the exact commit or the version.
  # uses: dlip/get-vercel-deployment-action@e300a2784474372f97ce5b95770ef2b4aee6469d
  uses: dlip/get-vercel-deployment-action@v1.0.2
  with:
    # Vercel token
    vercel-token: 
    # Vercel org id
    vercel-org-id: 
    # Vercel project id
    vercel-project-id: 
    # Github branch
    github-branch: 
    # Github commit commit
    github-commit: 
    # How long to wait to see deployment starting
    start-timeout: # optional, default is 600
    # How long to wait to see deployment finish
    finish-timeout: # optional, default is 600
    # How many pages to search for the deployment
    pagination-limit: # optional, default is 1
    # Should it wait until the deployment is ready
    wait: # optional, default is true
          
